"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, CheckCircle2, LoaderCircle, Sparkles } from "lucide-react";
import { CameraRecorder } from "@/components/camera-recorder";

function extensionFor(name:string,type:string){const ext=name.split(".").pop()?.toLowerCase();if(ext&&/^[a-z0-9]{1,8}$/.test(ext))return ext;if(type.includes("mp4"))return"mp4";if(type.includes("quicktime"))return"mov";return"webm"}
export function CreateWizard(){
  const router=useRouter(); const [step,setStep]=useState(1); const [video,setVideo]=useState<{blob:Blob;name:string}|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [uploadPct,setUploadPct]=useState(0);
  function selected(blob:Blob,name:string){setVideo({blob,name});setStep(2)}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!video)return;setBusy(true);setError("");setStep(3);try{const fd=new FormData(e.currentTarget);const payload={productName:String(fd.get("productName")||""),description:String(fd.get("description")||""),price:String(fd.get("price")||""),offer:String(fd.get("offer")||""),targetCustomer:String(fd.get("targetCustomer")||""),highlights:String(fd.get("highlights")||""),cta:String(fd.get("cta")||""),forbiddenInfo:String(fd.get("forbiddenInfo")||""),targetDuration:Number(fd.get("targetDuration")||30),styleKey:"natural_intro",subtitlesEnabled:true};const pRes=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const pJson=await pRes.json();if(!pRes.ok)throw new Error(pJson.error||"Không tạo được dự án");const projectId=pJson.project.id;setUploadPct(15);const contentType=video.blob.type||"video/webm";const sRes=await fetch("/api/uploads/presign",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,purpose:"source-video",contentType,extension:extensionFor(video.name,contentType),sizeBytes:video.blob.size})});const sJson=await sRes.json();if(!sRes.ok)throw new Error(sJson.error||"Không tạo được đường tải lên");setUploadPct(30);const put=await fetch(sJson.uploadUrl,{method:"PUT",headers:{"Content-Type":contentType},body:video.blob});if(!put.ok)throw new Error("Tải video lên storage thất bại");setUploadPct(65);const patch=await fetch(`/api/projects/${projectId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({sourceVideoKey:sJson.key})});if(!patch.ok)throw new Error("Không cập nhật được video nguồn");setUploadPct(80);const a=await fetch(`/api/projects/${projectId}/analyze`,{method:"POST"});const aj=await a.json();if(!a.ok)throw new Error(aj.error||"Không khởi động được phân tích");setUploadPct(100);router.push(`/projects/${projectId}`)}catch(err){setError(err instanceof Error?err.message:"Có lỗi xảy ra");setStep(2)}finally{setBusy(false)}}
  return <div className="card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><div className="flex items-center justify-between gap-2 text-xs font-bold text-slate-400"><span className={step>=1?"text-orange-600":""}>1. Video</span><span>→</span><span className={step>=2?"text-orange-600":""}>2. Sản phẩm</span><span>→</span><span className={step>=3?"text-orange-600":""}>3. AI phân tích</span></div></div>
    <div className="p-4 sm:p-7">{step===1&&<><div className="mb-5 text-center"><h2 className="text-xl font-black">Quay hoặc tải video sản phẩm</h2><p className="mt-1 text-sm text-slate-500">Video gốc chỉ là source. Hệ thống sẽ chuẩn hóa lại trước khi render.</p></div><CameraRecorder onVideo={selected}/></>}
    {step===2&&<form onSubmit={submit} className="mx-auto max-w-2xl"><div className="mb-6"><h2 className="text-xl font-black">Thông tin sản phẩm</h2><p className="mt-1 text-sm text-slate-500">Chỉ tên sản phẩm là bắt buộc. Thông tin bạn nhập sẽ được AI ưu tiên hơn suy đoán từ hình ảnh.</p></div><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Tên sản phẩm *</span><input name="productName" required className="input" placeholder="Ví dụ: Cây nho xanh 1 mét có trái"/></label><label className="sm:col-span-2"><span className="label">Mô tả ngắn</span><textarea name="description" rows={3} className="input" placeholder="Mô tả đúng những gì bạn biết về sản phẩm"/></label><label><span className="label">Giá</span><input name="price" className="input" placeholder="Ví dụ: 350.000đ"/></label><label><span className="label">Ưu đãi</span><input name="offer" className="input" placeholder="Ví dụ: freeship nội thành"/></label><label><span className="label">Khách hàng mục tiêu</span><input name="targetCustomer" className="input" placeholder="Ai phù hợp nhất?"/></label><label><span className="label">Điểm nổi bật</span><input name="highlights" className="input" placeholder="Điểm muốn nhấn mạnh"/></label><label><span className="label">CTA</span><input name="cta" className="input" placeholder="Nhắn tin, đặt hàng, xem thêm…"/></label><label><span className="label">Thời lượng mục tiêu</span><select name="targetDuration" className="input" defaultValue="30">{[15,30,45,60,90].map(x=><option key={x} value={x}>{x} giây</option>)}</select></label><label className="sm:col-span-2"><span className="label">Thông tin AI không được nói</span><textarea name="forbiddenInfo" rows={2} className="input" placeholder="Ví dụ: không khẳng định công dụng chữa bệnh, không tự đoán xuất xứ…"/></label></div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-6 flex gap-3"><button type="button" onClick={()=>setStep(1)} className="btn-secondary"><ArrowLeft size={17}/>Đổi video</button><button disabled={busy} className="btn-primary flex-1">Tải lên & phân tích <ArrowRight size={17}/></button></div></form>}
    {step===3&&<div className="mx-auto max-w-lg py-14 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-orange-50 text-orange-500">{uploadPct<100?<LoaderCircle className="animate-spin" size={34}/>:<CheckCircle2 size={34}/>}</div><h2 className="mt-5 text-xl font-black">Đang chuẩn bị dự án</h2><p className="mt-2 text-sm text-slate-500">Tải video lên storage an toàn, sau đó worker sẽ chuẩn hóa và gửi các frame đại diện cho AI Vision.</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-orange-500 transition-all" style={{width:`${uploadPct}%`}}/></div><p className="mt-2 text-xs font-bold text-slate-400">{uploadPct}%</p><div className="mt-5 inline-flex items-center gap-2 rounded-full bg-slate-50 px-4 py-2 text-xs font-bold text-slate-500"><Sparkles size={14}/>Không gửi toàn bộ video lên AI</div></div>}
    </div></div>
}
