"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Download, LoaderCircle, Mic2, Play, RefreshCw, Sparkles, WandSparkles } from "lucide-react";

const builtStyles=[
  ["natural_intro","Giới thiệu tự nhiên"],["ugc_tiktok","Review UGC / TikTok"],["problem_solution","Vấn đề → Giải pháp"],["demo","Demo / Hướng dẫn"],["story","Storytelling trải nghiệm"],["viral","Bắt trend / Viral"],["expert","Chuyên gia tư vấn"],["conversion","Bán hàng chuyển đổi"]
];
const statusName:Record<string,string>={UPLOADING:"Đang tải video",UPLOADED:"Video đã tải",ANALYZING:"AI đang phân tích",ANALYZED:"Chọn góc nội dung",GENERATING_SCRIPT:"AI đang viết kịch bản",SCRIPT_READY:"Kịch bản sẵn sàng",GENERATING_AUDIO:"Đang tạo giọng",AUDIO_READY:"Giọng đã sẵn sàng",RENDERING:"Đang dựng video",VALIDATING:"Đang kiểm tra video",COMPLETED:"Hoàn thành",FAILED:"Có lỗi cần thử lại"};
const refineActions:any[]=[["rewrite","Viết lại"],["shorter","Ngắn hơn"],["longer","Dài hơn"],["stronger_hook","Hook mạnh hơn"],["natural","Tự nhiên hơn"],["sales","Bán hàng hơn"]];

export function ProjectWorkspace({id}:{id:string}){
  const[data,setData]=useState<any>(null);const[voices,setVoices]=useState<any[]>([]);const[styles,setStyles]=useState<any[]>([]);const[selectedAngle,setSelectedAngle]=useState("");const[styleKey,setStyleKey]=useState("natural_intro");const[duration,setDuration]=useState(30);const[scriptText,setScriptText]=useState("");const[voiceId,setVoiceId]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");const[fileUrl,setFileUrl]=useState("");const[audioUrl,setAudioUrl]=useState("");
  const load=useCallback(async()=>{const[r,v,s]=await Promise.all([fetch(`/api/projects/${id}`,{cache:"no-store"}),fetch("/api/voices",{cache:"no-store"}),fetch("/api/styles",{cache:"no-store"})]);if(!r.ok)return;const j=await r.json();setData(j);setSelectedAngle(prev=>prev||j.project.selectedAngleId||j.angles.find((a:any)=>a.aiRecommended)?.id||j.angles[0]?.id||"");setStyleKey(j.project.styleKey||"natural_intro");setDuration(Number(j.project.targetDuration||30));const current=j.scripts.find((x:any)=>x.isCurrent)||j.scripts[0];setScriptText(prev=>prev||(current?.scriptText||""));if(v.ok){const vv=(await v.json()).voices||[];setVoices(vv);setVoiceId(prev=>prev||vv.find((x:any)=>x.isDefault)?.id||vv[0]?.id||"")}if(s.ok)setStyles((await s.json()).styles||[])},[id]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{if(!data)return;const live=["ANALYZING","GENERATING_SCRIPT","GENERATING_AUDIO","RENDERING","VALIDATING","UPLOADED"].includes(data.project.status);if(!live)return;const t=setInterval(load,3000);return()=>clearInterval(t)},[data,load]);
  useEffect(()=>{async function signed(){const out=data?.outputs?.[0]?.storageKey;if(out){const r=await fetch(`/api/files/download?key=${encodeURIComponent(out)}`);if(r.ok)setFileUrl((await r.json()).url)}const aud=data?.audios?.find((a:any)=>a.status==="READY")?.storageKey;if(aud){const r=await fetch(`/api/files/download?key=${encodeURIComponent(aud)}`);if(r.ok)setAudioUrl((await r.json()).url)}}signed()},[data]);
  const currentScript=useMemo(()=>data?.scripts?.find((x:any)=>x.isCurrent)||data?.scripts?.[0],[data]);
  async function call(url:string,body?:any,key="action"){setBusy(key);setError("");try{const r=await fetch(url,{method:"POST",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Không thể xử lý");await load()}catch(e){setError(e instanceof Error?e.message:"Có lỗi xảy ra")}finally{setBusy("")}}
  async function makeScript(){if(!selectedAngle){setError("Hãy chọn một góc nội dung.");return}await call(`/api/projects/${id}/script`,{angleId:selectedAngle,styleKey,targetDuration:duration},"script")}
  async function refine(action:string){if(!scriptText)return;setBusy(`refine-${action}`);setError("");try{const r=await fetch(`/api/projects/${id}/script/refine`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:scriptText,action})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Không chỉnh được kịch bản");setScriptText(j.text)}catch(e){setError(e instanceof Error?e.message:"Có lỗi xảy ra")}finally{setBusy("")}}
  async function saveScript(){const r=await fetch(`/api/projects/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({scriptText})});if(!r.ok)throw new Error("Không lưu được kịch bản")}
  async function makeAudio(){if(!voiceId){setError("Hãy thêm/chọn một giọng nói trước.");return}setBusy("audio");setError("");try{await saveScript();const r=await fetch(`/api/projects/${id}/audio`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({voiceId})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Không tạo được giọng");await load()}catch(e){setError(e instanceof Error?e.message:"Có lỗi xảy ra")}finally{setBusy("")}}
  async function render(){await call(`/api/projects/${id}/render`,undefined,"render")}
  if(!data)return <div className="card grid min-h-64 place-items-center"><LoaderCircle className="animate-spin text-orange-500"/></div>;
  const p=data.project;const processing=["ANALYZING","GENERATING_SCRIPT","GENERATING_AUDIO","RENDERING","VALIDATING"].includes(p.status);
  return <div className="space-y-5">
    <section className="card p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-orange-600"><Sparkles size={14}/>{statusName[p.status]||p.status}</div><h2 className="mt-2 text-2xl font-black">{p.productName}</h2><p className="mt-1 text-sm text-slate-500">{p.statusMessage}</p></div><button onClick={load} className="btn-secondary"><RefreshCw size={16}/>Làm mới</button></div><div className="mt-5 h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-orange-500 transition-all" style={{width:`${p.progress||0}%`}}/></div><div className="mt-2 text-right text-xs font-black text-slate-400">{p.progress||0}%</div></section>
    {error&&<div className="rounded-xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
    {processing&&<section className="card p-8 text-center"><LoaderCircle className="mx-auto animate-spin text-orange-500" size={34}/><h3 className="mt-4 font-black">{p.statusMessage}</h3><p className="mt-2 text-sm text-slate-500">Bạn có thể rời trang. Job chạy ở worker riêng và có retry.</p></section>}

    {data.angles?.length>0&&<section className="card p-5 sm:p-6"><div className="flex items-center gap-2"><WandSparkles className="text-orange-500"/><h3 className="text-lg font-black">Góc khai thác nội dung</h3></div><p className="mt-1 text-sm text-slate-500">Chọn một góc hoặc dùng góc AI gợi ý.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{data.angles.map((a:any)=><button key={a.id} onClick={()=>setSelectedAngle(a.id)} className={`text-left rounded-2xl border p-4 transition ${selectedAngle===a.id?"border-orange-400 bg-orange-50 ring-2 ring-orange-100":"border-slate-200 bg-white hover:border-slate-300"}`}><div className="flex items-center justify-between gap-2"><b>{a.title}</b>{a.aiRecommended&&<span className="rounded-full bg-orange-500 px-2 py-1 text-[10px] font-black text-white">AI CHỌN</span>}</div><p className="mt-2 text-sm font-semibold text-slate-700">{a.hook}</p><p className="mt-2 text-xs leading-relaxed text-slate-500">{a.insight}</p></button>)}</div>
      {!currentScript&&<div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><select className="input" value={styleKey} onChange={e=>setStyleKey(e.target.value)}>{builtStyles.map(([k,n])=><option key={k} value={k}>{n}</option>)}{styles.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="input" value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[15,30,45,60,90].map(x=><option key={x} value={x}>{x} giây</option>)}</select><button onClick={makeScript} disabled={!!busy} className="btn-primary">{busy==="script"?<LoaderCircle className="animate-spin" size={18}/>:<Sparkles size={18}/>}Viết kịch bản</button></div>}
    </section>}

    {currentScript&&<section className="card p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><h3 className="text-lg font-black">Kịch bản</h3><p className="text-sm text-slate-500">{p.targetDuration}s · phiên bản {currentScript.version}. TTS luôn dùng nội dung cuối bạn đang nhìn thấy.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{refineActions.map(([k,n])=><button key={k} onClick={()=>refine(k)} disabled={!!busy} className="btn-secondary !px-3 !py-2 text-xs">{busy===`refine-${k}`&&<LoaderCircle className="animate-spin" size={13}/>} {n}</button>)}</div><textarea value={scriptText} onChange={e=>setScriptText(e.target.value)} rows={10} className="input mt-4 leading-7"/>
      <div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><select value={voiceId} onChange={e=>setVoiceId(e.target.value)} className="input"><option value="">Chọn giọng nói</option>{voices.map(v=><option key={v.id} value={v.id}>{v.displayName} · {v.provider}</option>)}</select><button onClick={makeAudio} disabled={!!busy||p.status==="GENERATING_AUDIO"} className="btn-primary"><Mic2 size={18}/>{busy==="audio"?"Đang gửi…":"Tạo giọng từ bản này"}</button></div>{!voices.length&&<p className="mt-2 text-xs text-slate-500">Chưa có giọng. Hãy vào mục <a className="font-bold text-orange-600" href="/voices">Giọng nói</a> để thêm VBee hoặc clone ElevenLabs.</p>}
    </section>}

    {data.audios?.some((a:any)=>a.status==="READY")&&<section className="card p-5 sm:p-6"><div className="flex items-center gap-2"><Mic2 className="text-orange-500"/><h3 className="text-lg font-black">Audio đã sẵn sàng</h3></div>{audioUrl&&<audio className="mt-4 w-full" src={audioUrl} controls/>}<div className="mt-4 flex flex-wrap items-center gap-3"><button onClick={render} disabled={!!busy||["RENDERING","VALIDATING"].includes(p.status)} className="btn-primary"><Play size={18}/>{busy==="render"?"Đang gửi…":"Ghép & tạo video"}</button><label className="flex items-center gap-2 text-sm font-bold text-slate-600"><input type="checkbox" checked={p.subtitlesEnabled} onChange={async e=>{await fetch(`/api/projects/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({subtitlesEnabled:e.target.checked})});await load()}}/>Phụ đề</label></div></section>}

    {p.status==="COMPLETED"&&data.outputs?.length>0&&<section className="card overflow-hidden"><div className="p-5 sm:p-6"><div className="flex items-center gap-2 text-emerald-600"><CheckCircle2/><h3 className="text-lg font-black text-slate-900">Video đã vượt qua kiểm tra FFprobe</h3></div><p className="mt-1 text-sm text-slate-500">MP4 · H.264 · yuv420p · 1080×1920 · CFR 30fps · AAC 48kHz stereo · faststart.</p></div>{fileUrl&&<div className="bg-slate-950 p-4"><video className="mx-auto max-h-[70vh] rounded-xl" src={fileUrl} controls playsInline/></div>}<div className="p-5"><a href={fileUrl} download className="btn-primary w-full sm:w-auto"><Download size={18}/>Tải video MP4</a></div></section>}
  </div>
}
